travis:
  secure:
    BINSTAR_TOKEN: B65qY4zXh+VaJkiAZ2b4jjbYph9eP8+FPJ8B5moA1SXaJqZfyJ2fYKsdi4gf4qnREwxHZCuOr8rT8HBUx4v5mdIxDNssu08PIGal9Q/HVXmjoJxo/vC+Z3MrgBIp9MHQrObH/wgt/zkLKdwtZN2qomHovx4kbOSCqrQKCnJNirriZEOz3viQCrTzk+pq35mkMA4MWleASD3Lc9FGfsHhHcM6ITguZ2BlbDb9h+wUBupx24krO/M/ZaSq7E6Inns6K1vFPXvkRWMAWhfhkBWylTDxp6vottB+aVXZramsTeVYTowvUCJQE+NaVz4yaOW1jJIcqukJiDN+iS/oc9b1j4vHU+kr98gjxNTUWMF5PJ4CLdTKxViIF226azVkLiFP1ns7toL6lkuVYzGqBnjIz2Q4rW8BQUd8/080D9bDFTs0MXepatK06D+tGrM+XK3t0J3j/ktOZtv+mnaN4OhzNYOunBo4SYBIORNoiSrcj8fkjvVt+xUCSkqQdzjthV7prw0YJQOvKLGQbz+3baEXZZ55ta5j2dVlj0gIB04I5AVnDT03pPK7f6o9xITriYgI/OsjA43YapGaYRnVHVwH9LJEYXo3gTUA2peIZCaVe1E0nye1XdBSbN2drrYSydxmQwQ/ZHNJ1PyDqe9/vZU1+9+ZXh0VvHm2+sI7nQ9Yevo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
